### ISSUE TITLE
Add noImplicitAny in tsconfig.json

### ISSUE THREAD

**Issue by demurgos** [andrew-w-ross/typings-expect#3]
@andrew-w-ross 

Type definitions should be compiled with `noImplicitlyAny` to prevent errors in consumer code.

Currently, there are three implicit `any`s:
- https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts#L222
- https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts#L232
- https://github.com/andrew-w-ross/typings-expect/blob/master/expect.d.ts#L250

These should either be typed or explicitly marked as `any`

**Comment by andrew-w-ross** [comment]
@demurgos Ok fixed
